package com.mtucoursesmobile.michigantechcourses.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF735C00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE089)
val onPrimaryContainerLight = Color(0xFF241A00)
val secondaryLight = Color(0xFF1160A4)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2E4FF)
val onSecondaryContainerLight = Color(0xFF001C38)
val tertiaryLight = Color(0xFFA43D01)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCD)
val onTertiaryContainerLight = Color(0xFF360F00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFBFF)
val onBackgroundLight = Color(0xFF1E1B16)
val surfaceLight = Color(0xFFFFFBFF)
val onSurfaceLight = Color(0xFF1E1B16)
val outlineLight = Color(0xFF7D7667)
val surfaceVariantLight = Color(0xFFEBE1CF)
val onSurfaceVariantLight = Color(0xFF4C4639)

val primaryDark = Color(0xFFF0C100)
val onPrimaryDark = Color(0xFF3D2F00)
val primaryContainerDark = Color(0xFF574500)
val onPrimaryContainerDark = Color(0xFFFFE089)
val secondaryDark = Color(0xFFA1C9FF)
val onSecondaryDark = Color(0xFF00325B)
val secondaryContainerDark = Color(0xFF004880)
val onSecondaryContainerDark = Color(0xFFD2E4FF)
val tertiaryDark = Color(0xFFFFB597)
val onTertiaryDark = Color(0xFF581D00)
val tertiaryContainerDark = Color(0xFF7D2D00)
val onTertiaryContainerDark = Color(0xFFFFDBCD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1E1B16)
val onBackgroundDark = Color(0xFFE8E2D9)
val surfaceDark = Color(0xFF1E1B16)
val onSurfaceDark = Color(0xFFE8E2D9)
val outlineDark = Color(0xFF989080)
val surfaceVariantDark = Color(0xFF4C4639)
val onSurfaceVariantDark = Color(0xFFCFC6B4)